### PR TITLE
Use BCP 47 formatted string for locale

### PR DESCRIPTION
**Pull request by beastbytes**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️/❌

### CODE REVIEW

**Review by vjik — CHANGES_REQUESTED** [review]
Better use `en` instead `en-US` or `en_US`, because it's more common solution that will be good work with both cases.

**Comment by darkdef** [comment]
Sorry, but I don't agree. We use primarily the POSIX system,
On POSIX platforms such as Unix, Linux and others, locale identifiers are defined by ISO/IEC 15897, which is similar to the BCP 47

**Comment by darkdef** [comment]
Read this https://en.wikipedia.org/wiki/Locale_(computer_software). 
Section about POSIX

**Comment by samdark** [comment]
@beastbytes First of all, tyanks for contributing. What's the idea behind the pull request? Would you please elaborate a bit?

**Comment by samdark** [comment]
Fixed in https://github.com/yiisoft/translator/pull/110. Thanks for reporting it.

**Comment by darkdef** [comment]
@beastbytes I'm so sorry. I don't understood you. 
We fixed that bug.

**Pull request closed without merging**
